name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
      - name: Test
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn test
      - name: RUN
        run: node app.js