name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@latest
        with:
          args: yarn
      - name: RUN
        run: node app.js